name: tests
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
  workflow_dispatch:
jobs:
  unit:
    concurrency:
      group: unit-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22.x]
        os: [ubuntu, windows, macOS]
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Test
        run: go test -race -coverprofile report.txt -covermode atomic -skip Example -v ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./report.txt
          flags: unit,${{ matrix.os }},go-${{ matrix.go-version }},ydb-${{ matrix.ydb-version }}
  examples:
    concurrency:
      group: examples-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}-${{ matrix.ydb-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x, 1.22.x]
        os: [ubuntu]
        ydb-version: [24.1]
    services:
      ydb:
        image: ydbplatform/local-ydb:${{ matrix.ydb-version }}
        ports:
          - 2135:2135
          - 2136:2136
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
          YDB_TABLE_ENABLE_PREPARED_DDL: true
        options: '-h localhost'
    env:
      OS: ubuntu-latest
      GO: ${{ matrix.go-version }}
      YDB_VERSION: ${{ matrix.ydb-version }}
      YDB_CONNECTION_STRING: grpc://localhost:2136/local
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Test
        run: go test -race -coverprofile report.txt -covermode atomic -run Example -v ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./report.txt
          flags: examples,${{ matrix.os }},go-${{ matrix.go-version }},ydb-${{ matrix.ydb-version }}
